server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    h2:
      console:
        path: /h2
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate.ddl-auto: update
